project:
 type: website
 output-dir: docs
 resources:
  - papers/pdf/**

website:
 title: "Geometry, Optimization, Machine Learning and Stochastic"
 navbar:
  left:
   - href: index.qmd
     text: Home
   - href: papers.qmd
     text: Papers
   - href: proofs.qmd
     text: Proofs
   - href: blog.qmd
     text: Blog

format:
 html:
  theme: cosmo
  toc :  true