--- 
title: "What I learned from Guofan Zeng"
date: 2026-03-22
---
# What I learned from Guofan Zeng

Zengguo Fan is a very important court official in the late Qing Dynasty. It is undeniable that he made a tremendous contribution to china's development, but also someone thinks he is a
traitor, since he, as a  Han chinese, helped the Qing dynasty suppressed uprisings. I do not want to talk about his merits and demerits. Afterall, everyone has strengths and weaknesses. Besides being an 
official, he was also a Confucian scholar. I recently read some of his writings , which demonstrated his thoughts for many subjects. I'm particularly interested by his point of view about 
doing academic research and managing a household.

Zeng's said that, a good paper, should be written brightly and majesticly, make its reader feeling refreshed, and I totally agreed, I'll try my best to learn how to write a bright and majestic
paper. Another point of view about academic, is that for every subject we are interested in, we should study it in depth, and not just scratch the surface, which I shouled be very careful about this.
Because I'm actually interested in many topics and if not careful, I‘ll become someone who only scratches the surface.

About managing houseld, there are eight admonitions: getting up early, doing housework, sincerely performming sacrificail rites, treating clansmen well.  I think I'm doing well for the first``
two, but for the last two, I still need some work on them. 

For the last, I think Zeng's thoughts can be summarized in one word, **Respect**('敬' in chinese), that is, we should respect every thing we did and will do, we should give our all to
everyone and everything. I will strive to put his teaings into practice.

