---
title: "How to Find a Laboratory Internship in France"
date: 2026-03-28
---
# How to Find a Laboratory Internship in France

Finding an internship in a laboratory (lab) in France is not an easy thing, especially in a reputable lab. I'll give some tips according to my personal experience. First of all, make sure you really want to work in academia, which means that you were not forced to work in academia, e.g., you could not find an internship in industry and thought maybe an internship in a lab is easier to find. This is not the case we want to talk about.

Once you have made up your mind to work in a lab, then you can start to contact the professor you want to work with. There are many ways to get in touch with them, such as sending an email or finding someone you both know to help you. These two are the most popular ways to find an internship in a lab, especially in France, according to my personal experience.

Let me talk about the second way first. Finding someone you both know is the most direct way, but not necessarily the most possible way. In this case, whether you can find an internship almost only depends on the relationship between you and the person you find, and between that person and the professor. If the person you find is very familiar with the professor, and he has a good impression of you, not necessarily "very good", and he is willing to say a few nice things about you to the professor, then it's done, you get the job. In this case, you do not even need to send your CV and grades to the professor. But there is another case: if the person you find is not very familiar with you and says something general to the professor, then it is even worse than directly sending an email to the professor yourself.

If you cannot find anyone who is willing to help you, e.g., you just came to France one year ago to start your Master's program, the easiest way is to send emails to professors you are interested in one by one. To do this, you should know a little bit about which area you want to dive into. Then the next step is to start with a professor you are familiar with; in most cases, it is your course professor. Send him an email, and make sure to clarify which area you want to dive into in the email. Then there are two possibilities: he accepts you, and then it's done, congratulations.

If not, you need to find the next professor, but how? This is what I want to emphasize: you can search for your professor's name on Google Scholar, then find papers related to your area, and find co-authors from those papers who also live in France. Normally, they will leave their email addresses in the paper. Send them emails, then repeat this "iteration" until you find an internship. Noting that if you can get a recommendation letter from your course professor before starting the iteration, it will be much more helpful. Another tip for the interview: if it is possible, do the interview face-to-face, and try to avoid online interviews, also based on my personal experience. So the most difficult thing in this "iteration" is not finding someone, it is knowing which area you want to dive into in the future. Once you know that, it is natural to know who you want to work with.

Last thing, do not forget to make beautiful slides to show what you have done during the interview. Hope everyone can find an internship they like.