---
title: " How to find a laboratory internship in France "
date: 2026-03-28
---
# How to find a laboratory internship in France 

Find internship in laboratory(lab) in France is not a easy thing, especially in a reputational lab. I'll give some tips according to
my personal experience. First of all, make sure you really want to work in academia, which means that you were not 
forced to work in academia, e.g., you can not find internship in industry and thought may be an internship in lab is easier
to find, this is not the case we want to talk about.

Once you have made up your mind to work in the lab, then you can start to connect the professor you want to work with. 
There are many ways to get in touch with them, send email or find someone you both know to help you, these two are the most popular ways
to find a intern in lab especially in France, according to my personal experience. 

Let me talk about the second way frist. Find someone you both know is the most direct way, but not
necessarily the most possible way. In this case, whether you can find an internship almost only depends on
the relationship bewteen you and the one you find  , and between the one you find and the professor. If the one you find is 
very familiar with the professor, and he has a good impression with you, not necessarily "very good", and he is willing
to say a few nice things to you with the professor, then its done, you get the job. In this case, you even do not need 
to send you CV and grades to the professor. But there is another case, the one you find is not very familiar with you 
and say something genenral to the professor, then it is even worse than directly send an email to the professor yourself.

If you can not find any one who is willing to help you, e.g., you just came to France one year ago to start your 
Master programe, the most easier way is to send eamail to professors you are interested in one by one. 
To do this, you should know a liitle bit which area you want to dive into.
Then next is start from a professor you are familiar with, for most of the case,  it is your course professor.
Send him an eamail, make sure to clarify which area you want dive into in the email. Then there are possibilities, he accept you, then its done, congratulations.
If not, you need to find next professor, but how? This is what I want to emphasize, you can search your professor's name from google scholar, 
then find the paper related with your area, find the co-author from the paper who also lived in France, normally, they will leave their eamail
in the paper, send them eamil, then repeat is "iteration", until you find internship. Noting that, if you can get 
a recomendation letter from your course professor before starting the iteration, it will be much helpful. Another tip for 
interview, if it is possible, do interview face-to-face, try to avoid online interview, also extracted from my personal experience.
So the most diffucity thing in this "iteration" is not finding someone, it is to know which aera you want to dive into in the future,
once you know that, it is a natural thing knowing who you want to work with. 

Last thing, do not forget to do a beautiful slides to show what you have done during interview. Hope everyone can find intership you like. 

